name: filament-trilist

services:
  app:
    build:
      dockerfile: Dockerfile
    environment:
      SERVER_NAME: ':80'
      SERVER_ROOT: 'demo/public/'
    ports:
      - 80:80
    tty: true
    volumes:
      - './volumes/caddy_data:/data'
      - './volumes/caddy_config:/config'
      - '..:/app'
